/*
 * This file is generated by jOOQ.
 */
package be.app.sb.db.tables.records;


import be.app.sb.db.tables.Employee;

import java.time.LocalDate;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeeRecord extends UpdatableRecordImpl<EmployeeRecord> implements Record10<Integer, String, LocalDate, String, String, String, LocalDate, String, String, Integer> {

    private static final long serialVersionUID = 901119257;

    /**
     * Setter for <code>EMPLOYEE.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>EMPLOYEE.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>EMPLOYEE.USER_NAME</code>.
     */
    public void setUserName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>EMPLOYEE.USER_NAME</code>.
     */
    public String getUserName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>EMPLOYEE.BIRTH_DATE</code>.
     */
    public void setBirthDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>EMPLOYEE.BIRTH_DATE</code>.
     */
    public LocalDate getBirthDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>EMPLOYEE.FIRST_NAME</code>.
     */
    public void setFirstName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>EMPLOYEE.FIRST_NAME</code>.
     */
    public String getFirstName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>EMPLOYEE.LAST_NAME</code>.
     */
    public void setLastName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>EMPLOYEE.LAST_NAME</code>.
     */
    public String getLastName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>EMPLOYEE.GENDER</code>.
     */
    public void setGender(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>EMPLOYEE.GENDER</code>.
     */
    public String getGender() {
        return (String) get(5);
    }

    /**
     * Setter for <code>EMPLOYEE.HIRE_DATE</code>.
     */
    public void setHireDate(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>EMPLOYEE.HIRE_DATE</code>.
     */
    public LocalDate getHireDate() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>EMPLOYEE.PASSWORD</code>.
     */
    public void setPassword(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>EMPLOYEE.PASSWORD</code>.
     */
    public String getPassword() {
        return (String) get(7);
    }

    /**
     * Setter for <code>EMPLOYEE.ROLE</code>.
     */
    public void setRole(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>EMPLOYEE.ROLE</code>.
     */
    public String getRole() {
        return (String) get(8);
    }

    /**
     * Setter for <code>EMPLOYEE.DEPARTMENT_ID</code>.
     */
    public void setDepartmentId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>EMPLOYEE.DEPARTMENT_ID</code>.
     */
    public Integer getDepartmentId() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, LocalDate, String, String, String, LocalDate, String, String, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, LocalDate, String, String, String, LocalDate, String, String, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Employee.EMPLOYEE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Employee.EMPLOYEE.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDate> field3() {
        return Employee.EMPLOYEE.BIRTH_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Employee.EMPLOYEE.FIRST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Employee.EMPLOYEE.LAST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Employee.EMPLOYEE.GENDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDate> field7() {
        return Employee.EMPLOYEE.HIRE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Employee.EMPLOYEE.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Employee.EMPLOYEE.ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Employee.EMPLOYEE.DEPARTMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate component3() {
        return getBirthDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate component7() {
        return getHireDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getDepartmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate value3() {
        return getBirthDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate value7() {
        return getHireDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getDepartmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord value2(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord value3(LocalDate value) {
        setBirthDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord value4(String value) {
        setFirstName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord value5(String value) {
        setLastName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord value6(String value) {
        setGender(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord value7(LocalDate value) {
        setHireDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord value8(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord value9(String value) {
        setRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord value10(Integer value) {
        setDepartmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord values(Integer value1, String value2, LocalDate value3, String value4, String value5, String value6, LocalDate value7, String value8, String value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeeRecord
     */
    public EmployeeRecord() {
        super(Employee.EMPLOYEE);
    }

    /**
     * Create a detached, initialised EmployeeRecord
     */
    public EmployeeRecord(Integer id, String userName, LocalDate birthDate, String firstName, String lastName, String gender, LocalDate hireDate, String password, String role, Integer departmentId) {
        super(Employee.EMPLOYEE);

        set(0, id);
        set(1, userName);
        set(2, birthDate);
        set(3, firstName);
        set(4, lastName);
        set(5, gender);
        set(6, hireDate);
        set(7, password);
        set(8, role);
        set(9, departmentId);
    }
}
