/*
 * This file is generated by jOOQ.
 */
package be.app.sb.db.tables.records;


import be.app.sb.db.tables.Timereport;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimereportRecord extends UpdatableRecordImpl<TimereportRecord> implements Record6<Integer, String, String, String, Integer, LocalDateTime> {

    private static final long serialVersionUID = 1189846400;

    /**
     * Setter for <code>TIMEREPORT.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>TIMEREPORT.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TIMEREPORT.USER_NAME</code>.
     */
    public void setUserName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>TIMEREPORT.USER_NAME</code>.
     */
    public String getUserName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>TIMEREPORT.DEPARTMENT_NAME</code>.
     */
    public void setDepartmentName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>TIMEREPORT.DEPARTMENT_NAME</code>.
     */
    public String getDepartmentName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>TIMEREPORT.PROJECT_NAME</code>.
     */
    public void setProjectName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>TIMEREPORT.PROJECT_NAME</code>.
     */
    public String getProjectName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>TIMEREPORT.NB_HOURS</code>.
     */
    public void setNbHours(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>TIMEREPORT.NB_HOURS</code>.
     */
    public Integer getNbHours() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>TIMEREPORT.REPORTED_TIME</code>.
     */
    public void setReportedTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>TIMEREPORT.REPORTED_TIME</code>.
     */
    public LocalDateTime getReportedTime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, Integer, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, Integer, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Timereport.TIMEREPORT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Timereport.TIMEREPORT.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Timereport.TIMEREPORT.DEPARTMENT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Timereport.TIMEREPORT.PROJECT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Timereport.TIMEREPORT.NB_HOURS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return Timereport.TIMEREPORT.REPORTED_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDepartmentName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getProjectName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getNbHours();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component6() {
        return getReportedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDepartmentName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getProjectName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getNbHours();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getReportedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TimereportRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TimereportRecord value2(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TimereportRecord value3(String value) {
        setDepartmentName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TimereportRecord value4(String value) {
        setProjectName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TimereportRecord value5(Integer value) {
        setNbHours(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TimereportRecord value6(LocalDateTime value) {
        setReportedTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TimereportRecord values(Integer value1, String value2, String value3, String value4, Integer value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TimereportRecord
     */
    public TimereportRecord() {
        super(Timereport.TIMEREPORT);
    }

    /**
     * Create a detached, initialised TimereportRecord
     */
    public TimereportRecord(Integer id, String userName, String departmentName, String projectName, Integer nbHours, LocalDateTime reportedTime) {
        super(Timereport.TIMEREPORT);

        set(0, id);
        set(1, userName);
        set(2, departmentName);
        set(3, projectName);
        set(4, nbHours);
        set(5, reportedTime);
    }
}
