/*
 * This file is generated by jOOQ.
 */
package be.app.sb.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Timereport implements Serializable {

    private static final long serialVersionUID = -419470481;

    private Integer       id;
    private String        userName;
    private String        departmentName;
    private String        projectName;
    private Integer       nbHours;
    private LocalDateTime reportedTime;

    public Timereport() {}

    public Timereport(Timereport value) {
        this.id = value.id;
        this.userName = value.userName;
        this.departmentName = value.departmentName;
        this.projectName = value.projectName;
        this.nbHours = value.nbHours;
        this.reportedTime = value.reportedTime;
    }

    public Timereport(
        Integer       id,
        String        userName,
        String        departmentName,
        String        projectName,
        Integer       nbHours,
        LocalDateTime reportedTime
    ) {
        this.id = id;
        this.userName = userName;
        this.departmentName = departmentName;
        this.projectName = projectName;
        this.nbHours = nbHours;
        this.reportedTime = reportedTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getDepartmentName() {
        return this.departmentName;
    }

    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    public String getProjectName() {
        return this.projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public Integer getNbHours() {
        return this.nbHours;
    }

    public void setNbHours(Integer nbHours) {
        this.nbHours = nbHours;
    }

    public LocalDateTime getReportedTime() {
        return this.reportedTime;
    }

    public void setReportedTime(LocalDateTime reportedTime) {
        this.reportedTime = reportedTime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Timereport other = (Timereport) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (userName == null) {
            if (other.userName != null)
                return false;
        }
        else if (!userName.equals(other.userName))
            return false;
        if (departmentName == null) {
            if (other.departmentName != null)
                return false;
        }
        else if (!departmentName.equals(other.departmentName))
            return false;
        if (projectName == null) {
            if (other.projectName != null)
                return false;
        }
        else if (!projectName.equals(other.projectName))
            return false;
        if (nbHours == null) {
            if (other.nbHours != null)
                return false;
        }
        else if (!nbHours.equals(other.nbHours))
            return false;
        if (reportedTime == null) {
            if (other.reportedTime != null)
                return false;
        }
        else if (!reportedTime.equals(other.reportedTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userName == null) ? 0 : this.userName.hashCode());
        result = prime * result + ((this.departmentName == null) ? 0 : this.departmentName.hashCode());
        result = prime * result + ((this.projectName == null) ? 0 : this.projectName.hashCode());
        result = prime * result + ((this.nbHours == null) ? 0 : this.nbHours.hashCode());
        result = prime * result + ((this.reportedTime == null) ? 0 : this.reportedTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Timereport (");

        sb.append(id);
        sb.append(", ").append(userName);
        sb.append(", ").append(departmentName);
        sb.append(", ").append(projectName);
        sb.append(", ").append(nbHours);
        sb.append(", ").append(reportedTime);

        sb.append(")");
        return sb.toString();
    }
}
