/*
 * This file is generated by jOOQ.
 */
package be.app.sb.db;


import be.app.sb.db.tables.Department;
import be.app.sb.db.tables.Employee;
import be.app.sb.db.tables.Timereport;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = -1913347699;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>DEPARTMENT</code>.
     */
    public final Department DEPARTMENT = be.app.sb.db.tables.Department.DEPARTMENT;

    /**
     * The table <code>EMPLOYEE</code>.
     */
    public final Employee EMPLOYEE = be.app.sb.db.tables.Employee.EMPLOYEE;

    /**
     * The table <code>TIMEREPORT</code>.
     */
    public final Timereport TIMEREPORT = be.app.sb.db.tables.Timereport.TIMEREPORT;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Department.DEPARTMENT,
            Employee.EMPLOYEE,
            Timereport.TIMEREPORT);
    }
}
