/*
 * This file is generated by jOOQ.
 */
package be.app.sb.db;


import be.app.sb.db.tables.Department;
import be.app.sb.db.tables.Employee;
import be.app.sb.db.tables.Timereport;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_4 = Indexes0.PRIMARY_KEY_4;
    public static final Index CONSTRAINT_75_INDEX_F = Indexes0.CONSTRAINT_75_INDEX_F;
    public static final Index PRIMARY_KEY_F = Indexes0.PRIMARY_KEY_F;
    public static final Index PRIMARY_KEY_8 = Indexes0.PRIMARY_KEY_8;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRIMARY_KEY_4 = Internal.createIndex("PRIMARY_KEY_4", Department.DEPARTMENT, new OrderField[] { Department.DEPARTMENT.ID }, true);
        public static Index CONSTRAINT_75_INDEX_F = Internal.createIndex("CONSTRAINT_75_INDEX_F", Employee.EMPLOYEE, new OrderField[] { Employee.EMPLOYEE.USER_NAME }, true);
        public static Index PRIMARY_KEY_F = Internal.createIndex("PRIMARY_KEY_F", Employee.EMPLOYEE, new OrderField[] { Employee.EMPLOYEE.ID }, true);
        public static Index PRIMARY_KEY_8 = Internal.createIndex("PRIMARY_KEY_8", Timereport.TIMEREPORT, new OrderField[] { Timereport.TIMEREPORT.ID }, true);
    }
}
