/*
 * This file is generated by jOOQ.
 */
package be.app.sb.db;


import be.app.sb.db.tables.Department;
import be.app.sb.db.tables.Employee;
import be.app.sb.db.tables.Timereport;
import be.app.sb.db.tables.records.DepartmentRecord;
import be.app.sb.db.tables.records.EmployeeRecord;
import be.app.sb.db.tables.records.TimereportRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<DepartmentRecord, Integer> IDENTITY_DEPARTMENT = Identities0.IDENTITY_DEPARTMENT;
    public static final Identity<EmployeeRecord, Integer> IDENTITY_EMPLOYEE = Identities0.IDENTITY_EMPLOYEE;
    public static final Identity<TimereportRecord, Integer> IDENTITY_TIMEREPORT = Identities0.IDENTITY_TIMEREPORT;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DepartmentRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;
    public static final UniqueKey<EmployeeRecord> CONSTRAINT_7 = UniqueKeys0.CONSTRAINT_7;
    public static final UniqueKey<EmployeeRecord> CONSTRAINT_75 = UniqueKeys0.CONSTRAINT_75;
    public static final UniqueKey<TimereportRecord> CONSTRAINT_8 = UniqueKeys0.CONSTRAINT_8;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<DepartmentRecord, Integer> IDENTITY_DEPARTMENT = Internal.createIdentity(Department.DEPARTMENT, Department.DEPARTMENT.ID);
        public static Identity<EmployeeRecord, Integer> IDENTITY_EMPLOYEE = Internal.createIdentity(Employee.EMPLOYEE, Employee.EMPLOYEE.ID);
        public static Identity<TimereportRecord, Integer> IDENTITY_TIMEREPORT = Internal.createIdentity(Timereport.TIMEREPORT, Timereport.TIMEREPORT.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<DepartmentRecord> CONSTRAINT_4 = Internal.createUniqueKey(Department.DEPARTMENT, "CONSTRAINT_4", Department.DEPARTMENT.ID);
        public static final UniqueKey<EmployeeRecord> CONSTRAINT_7 = Internal.createUniqueKey(Employee.EMPLOYEE, "CONSTRAINT_7", Employee.EMPLOYEE.ID);
        public static final UniqueKey<EmployeeRecord> CONSTRAINT_75 = Internal.createUniqueKey(Employee.EMPLOYEE, "CONSTRAINT_75", Employee.EMPLOYEE.USER_NAME);
        public static final UniqueKey<TimereportRecord> CONSTRAINT_8 = Internal.createUniqueKey(Timereport.TIMEREPORT, "CONSTRAINT_8", Timereport.TIMEREPORT.ID);
    }
}
