/*
 * This file is generated by jOOQ.
 */
package be.app.sb.db;


import be.app.sb.db.tables.Department;
import be.app.sb.db.tables.Employee;
import be.app.sb.db.tables.Timereport;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>DEPARTMENT</code>.
     */
    public static final Department DEPARTMENT = be.app.sb.db.tables.Department.DEPARTMENT;

    /**
     * The table <code>EMPLOYEE</code>.
     */
    public static final Employee EMPLOYEE = be.app.sb.db.tables.Employee.EMPLOYEE;

    /**
     * The table <code>TIMEREPORT</code>.
     */
    public static final Timereport TIMEREPORT = be.app.sb.db.tables.Timereport.TIMEREPORT;
}
