/*
 * This file is generated by jOOQ.
 */
package be.app.sb.db.tables.daos;


import be.app.sb.db.tables.Timereport;
import be.app.sb.db.tables.records.TimereportRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimereportDao extends DAOImpl<TimereportRecord, be.app.sb.db.tables.pojos.Timereport, Integer> {

    /**
     * Create a new TimereportDao without any configuration
     */
    public TimereportDao() {
        super(Timereport.TIMEREPORT, be.app.sb.db.tables.pojos.Timereport.class);
    }

    /**
     * Create a new TimereportDao with an attached configuration
     */
    public TimereportDao(Configuration configuration) {
        super(Timereport.TIMEREPORT, be.app.sb.db.tables.pojos.Timereport.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(be.app.sb.db.tables.pojos.Timereport object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<be.app.sb.db.tables.pojos.Timereport> fetchById(Integer... values) {
        return fetch(Timereport.TIMEREPORT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public be.app.sb.db.tables.pojos.Timereport fetchOneById(Integer value) {
        return fetchOne(Timereport.TIMEREPORT.ID, value);
    }

    /**
     * Fetch records that have <code>USER_NAME IN (values)</code>
     */
    public List<be.app.sb.db.tables.pojos.Timereport> fetchByUserName(String... values) {
        return fetch(Timereport.TIMEREPORT.USER_NAME, values);
    }

    /**
     * Fetch records that have <code>DEPARTMENT_NAME IN (values)</code>
     */
    public List<be.app.sb.db.tables.pojos.Timereport> fetchByDepartmentName(String... values) {
        return fetch(Timereport.TIMEREPORT.DEPARTMENT_NAME, values);
    }

    /**
     * Fetch records that have <code>PROJECT_NAME IN (values)</code>
     */
    public List<be.app.sb.db.tables.pojos.Timereport> fetchByProjectName(String... values) {
        return fetch(Timereport.TIMEREPORT.PROJECT_NAME, values);
    }

    /**
     * Fetch records that have <code>NB_HOURS IN (values)</code>
     */
    public List<be.app.sb.db.tables.pojos.Timereport> fetchByNbHours(Integer... values) {
        return fetch(Timereport.TIMEREPORT.NB_HOURS, values);
    }

    /**
     * Fetch records that have <code>REPORTED_TIME IN (values)</code>
     */
    public List<be.app.sb.db.tables.pojos.Timereport> fetchByReportedTime(LocalDateTime... values) {
        return fetch(Timereport.TIMEREPORT.REPORTED_TIME, values);
    }
}
